### PR TITLE
Fix get Lazy<IOrganizationService> from IServiceProvider

### LINKED ISSUE #62: Required Type for Defaults Missing from IIocContainer
**Package:** DLaB.Xrm.Source
**Version:** v4.0.0.8

`DLaBGenericPluginBase` invokes `RegisterDataversePluginDefaults`, which attempts to get the following type from the `IServiceProvider` that is not registered.

### `Lazy<IOrganizationService>`

This is caused by [`DLaB.Xrm.Plugin.IocExtensions:86`](https://github.com/daryllabar/DLaB.Xrm/blob/3b93795041e73fba32fb3a5213ccd8b131963fac/DLaB.Xrm.Core/Plugin/IocExtensions.cs#L86), where the type `Lazy<IOrganizationService>` is being requested. This can be fixed by instantiating `Lazy` and returning a lambda that requests `IOrganizationService`.

```csharp
new Lazy<IOrganizationService>(() => s.Get<IOrganizationService>())
```

### PR DESCRIPTION
**Pull request by clurdish**
Fixes #62

### CODE REVIEW

**Review by daryllabar — COMMENTED** [review]
This shouldn't be making a difference, unless you have explicitly registered an `Lazy<IOrganizationService>`, that is different than `new Lazy<IOrganizationService>(() => s.Get<IOrganizationService>())`,  The provider built by the IOC container is assumed to be able to auto registered lazy implementations from the non-lazy version.

**Comment by clurdish** [comment]
Right now, I'm seeing the request getting forwarded to the core IServiceProvider before attempting to resolve it internally. While I agree this shouldn't be 100% necessary, this is causing issues with the testing harness we use.

Out of curiosity, what's the reason we want services to be resolved wrapped in `Lazy`?

**Comment by daryllabar** [comment]
So is the issue that your "Default" IServiceProvider is throwing an exception when an attempt to retrieve an ILazy<IOrganizationService> occurs, rather than just returning null, which is what I assume should happen?  

As to the reason why, just less to go through and define.  It would be a rare instance where you'd want the ILazy<T> to be different than the <T>, so why not just do it?

**Comment by clurdish** [comment]
My question is moreso what's the reason we'd want to have this sort of "hidden" behavior for the IServiceProvider? Is it that common that we need to get services wrapped in Lazy?

**Comment by daryllabar** [comment]
Primarily it helps to reduce infinite dependency loops.  If we have this:
```cs
public ClassConstructor1(ClassConstructor2 item) {}
public ClassConstructor2(ClassConstructor1 item) {}
```
we wouldn't be able to resolve it, but if we had

```cs
public ClassConstructor1(Lazy<ClassConstructor2> item) {}
public ClassConstructor2(Lazy<ClassConstructor2> item) {}
```
it would.

**Comment by daryllabar** [comment]
For now, I don't see a need to implement this change.  The OOB IServiceProvider in the plugin returns null if it doesn't know how to create something, so it's a flaw in your test harnesses implementation of the IServiceProvider, to not mimic the documented functionality of the system.  Plus, there is a simple work around to just add your registrations manually in your own code as a "work around".  Feel free to try and #ChangeMyMind ;)

**Comment by clurdish** [comment]
I agree that the test harness should return null in this scenario, and I have already created an [issue](https://github.com/DynamicsValue/fake-xrm-easy/issues/127) in that project for the same.

However, I don't necessarily agree that Lazy should be automatically evaluated if not registered with the service container. I would argue that closer parity with .NET's built-in service container would be clearer for developers coming from a standard .NET development background. But that's a separate issue.

**Pull request closed without merging**
